accounts/urls.py
from django.urls import path

from . import views
from .api import views as api_views

app_name = 'accounts'

urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('login/', views.UserLoginView.as_view(), name="login"),
    path('connect-github/', views.ConnectGithubView.as_view(), name='connect_github'),
    path('disconnect-github/', views.DisconnectGithubAccount.as_view(), name='disconnect_github'),
    path('my_account/', views.UserAccountUpdateView.as_view(), name='my_account'),
    path('register/', views.UserRegisterView.as_view(), name="register"),
    path('update-integration/', views.UpdateIntegrationView.as_view(), name='update_integration'),

    # api views
    path('api/v1/users_without_github/', api_views.UsersWithoutGithubView.as_view(), name='api_users_without_github'),
]

apigator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('auth/', include('allauth.urls')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.home, name="home"),
    path("github/create-repo/", views.CreateGitHubRepo.as_view(), name="github_create_repo"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class GPTIntegration(models.Model):
    """
    GPT integration for user
    """
    key = models.TextField(null=False, blank=False, help_text='GPT integration')
    organization_id = models.TextField(null=True, blank=True, help_text='GPT Organization ID')
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.key


# Create your models here.
class AccountIntegration(models.Model):
    """
    This model will be used as Integration Bridge Between User and Different Custom Integration Methods
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE, help_text='Users integration')
    gpt_integration = models.ForeignKey(GPTIntegration, on_delete=models.CASCADE, null=True, blank=True)
    integration_activity = models.JSONField(null=True, blank=True, help_text='For storing connection/re-connection activity')
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    """
    Form for login
    """
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(UserCreationForm):
    """
    Form for User Registration
    """
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserAccountUpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=30, disabled=True)
    email = forms.EmailField(disabled=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

accounts/api/views.py
# views.py
from rest_framework import generics
from .serializers import UserSerializer
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialAccount

class UsersWithoutGithubView(generics.ListAPIView):
    serializer_class = UserSerializer

    def get_queryset(self):
        return User.objects.exclude(id__in=SocialAccount.objects.filter(provider='github').values('user'))

accounts/views.py
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView
from django.views.generic.edit import UpdateView

from .forms import UserAccountUpdateForm, UserLoginForm, UserRegisterForm
from .models import AccountIntegration, GPTIntegration
from .mixins import UnauthenticatedUserMixin

from apigator.utils.logger import log_info, log_custom_error

import json


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('core:home')


class UserLoginView(UnauthenticatedUserMixin, FormView):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('core:home')  # Change this to your desired URL

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)


class UserRegisterView(UnauthenticatedUserMixin, FormView):
    form_class = UserRegisterForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('core:home')  # Change this to your desired URL

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


class UserAccountUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserAccountUpdateForm
    template_name = 'accounts/my_account.html'
    success_url = reverse_lazy('accounts:my_account')

    def get_object(self):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['github_connected'] = SocialAccount.objects.filter(user=self.request.user, provider='github').exists()

        integration_query = AccountIntegration.objects.filter(user=self.request.user)

        if integration_query.exists():
            context['integration_exists'] = True

            if integration_query.first().gpt_integration:
                context['gpt_integration_key'] = integration_query.first().gpt_integration.key
                context['organization_id'] = integration_query.first().gpt_integration.organization_id
        else:
            context['integration_exists'] = False
        return context


class ConnectGithubView(LoginRequiredMixin, View):
    def get(self, request):
        return redirect('socialaccount_connections')  # This is the url name for the Django AllAuth connections view
    

class DisconnectGithubAccount(View):
    def get(self, request):
        try:
            user = User.objects.get(id=request.user.id)
            social_account = SocialAccount.objects.get(user=user, provider='github')
            social_account.delete()

            user.github_account_linked = False
            user.save()

            return redirect('accounts:my_account')

        except SocialAccount.DoesNotExist:
            return redirect('accounts:my_account')

        except Exception as e:
            return redirect('accounts:my_account')


class UpdateIntegrationView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        key = request.POST.get("key")
        organization_id = request.POST.get('org_id')
        integration_query = AccountIntegration.objects.filter(user=self.request.user)
        if integration_query.exists():
            integration_obj = integration_query.first()
        else:
            integration_obj = AccountIntegration.objects.create(user=self.request.user)

        if integration_obj.gpt_integration:
            integration_obj.gpt_integration.key = key
            integration_obj.gpt_integration.organization_id = organization_id
            integration_obj.gpt_integration.save()

            # create activity
            # activity = json.loads(integration_obj.activity
        else:
            gpt_integration = GPTIntegration.objects.create(key=key, organization_id=organization_id)
            integration_obj.gpt_integration = gpt_integration
            integration_obj.save()

        return redirect('accounts:my_account')

templates/accounts/login.html
{% extends 'base.html' %}
{% load socialaccount %}

{% block page_title %}
Login
{% endblock page_title %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card mt-5">
        <div class="card-header">
          <h3>Login</h3>
        </div>
        <div class="card-body">
          {% include 'components/forms/login_form.html' %}
          <hr />
          Or 
          <hr />
          <a href="{% provider_login_url 'github' %}" class="btn btn-dark">
            <i class="fab fa-github"></i> Sign in with GitHub
          </a>
          
        </div>
        <div class="card-footer">
          <p>Don't have an account yet? <a href="{% url 'accounts:register' %}">Register now</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/accounts/my_account.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h2>My Account</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
    <hr class="my-4">
    <h3>Connected Accounts</h3>
    {% if github_connected %}
        <p>Github: Connected <br />  <a href="{% url 'accounts:disconnect_github' %}" class="btn btn-warning mt-3">Disconnect GitHub</a></p>
    {% else %}
        <p class="mt-4">Github: <a href="{% url 'accounts:connect_github' %}" class="btn btn-dark ml-5">
            <i class="fab fa-github"></i> Connect GitHub Now
          </a></p>
    {% endif %}
    <hr class="my-4">
    <h3>Integrations</h3>
    <form method="post" name='gpt_integration_key_form' action="{% url 'accounts:update_integration' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for='gpt_integration_key'>Enter GPT Integration Key</label>
            {% if integration_exists %}
                <input class="form-control" name='key' type='text' id='gpt_integration_key' value="{{ gpt_integration_key }}">
            {% else %}
                <input class="form-control" name='key' type='text' id='gpt_integration_key'>
            {% endif %}
        </div>
        <div class="form-group">
            <label for='organization_id'>Enter Organization ID</label>
            {% if integration_exists %}
                <input class="form-control" name='org_id' type='text' id='organization_id' value="{{ organization_id }}">
            {% else %}
                <input class="form-control" name='org_id' type='text' id='organization_id'>
            {% endif %}
        </div>
        {% if integration_exists %}
            <button class="btn btn-primary" type='submit'>Update Integration</button>
        {% else %}
            <button class="btn btn-primary" type='submit'>Create Integration</button>
        {% endif %}
    </form>    
</div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block page_title %}
Create new account
{% endblock page_title %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card mt-5">
        <div class="card-header">
          <h3>Create new account</h3>
        </div>
        <div class="card-body">
          {% include 'components/forms/registration_form.html' %}
        </div>
        <div class="card-footer">
          <p>Registered Already <a href="{% url 'accounts:login' %}">Login here</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}