accounts/urls.py
from django.urls import path

from . import views
from .api import views as api_views

app_name = 'accounts'

urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('login/', views.UserLoginView.as_view(), name="login"),
    path('connect-github/', views.ConnectGithubView.as_view(), name='connect_github'),
    path('disconnect-github/', views.DisconnectGithubAccount.as_view(), name='disconnect_github'),
    path('my_account/', views.UserAccountUpdateView.as_view(), name='my_account'),
    path('register/', views.UserRegisterView.as_view(), name="register"),
    path('update-integration/', views.UpdateIntegrationView.as_view(), name='update_integration'),

    # api views
    path('api/v1/users_without_github/', api_views.UsersWithoutGithubView.as_view(), name='api_users_without_github'),
]

apigator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('auth/', include('allauth.urls')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.home, name="home"),
    path("github/create-repo/", views.CreateGitHubRepo.as_view(), name="github_create_repo"),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.views import View

from allauth.socialaccount.models import SocialApp, SocialToken, SocialAccount

from accounts.models import *

from apigator.utils import gpt_requestor, git_manager, social, logger

# Create your views here.
@login_required(login_url='accounts:login')
def home(request):
    integration_query = AccountIntegration.objects.filter(user=request.user)
    context = {}

    if integration_query.exists():
        context['integration'] = True
        if integration_query.first().gpt_integration:
            # Getting required data from User's DB
            organization_id = integration_query.first().gpt_integration.organization_id
            key = integration_query.first().gpt_integration.key

            # Initializing GPT Requestor
            requestor = gpt_requestor.GPTRequestor(key, organization_id)

            # Checking for authorization
            authorizor_resp = requestor.check_authorization()
            context['authorized'] = authorizor_resp['status']

            if not authorizor_resp['status']:
                context['authorization_error_message'] = authorizor_resp['message']
    else:
        context['integration'] = False
        context['integration_error_message'] = 'You have not integrated GPT yet.'

    return render(request, 'core/home.html', context)


class CreateGitHubRepo(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        repo_name = request.POST.get('repo_name')
        repo_description = request.POST.get('repo_description')

        # authenticate github to get access_token

        # social_token = social.get_user_github_token(request.user)
        # github_manager = git_manager.GithubManager(access_token, repo_name, repo_description)
        # github_manager.create_github_repo()
        return redirect('core:home')

templates/core/home.html
{% extends 'base.html' %}

{% block page_title %}
Home
{% endblock page_title %}

{% block content %}

<div class="container pt-5">
{% if integration %}
    {% if authorized %}
    <h3>Create Github Repo</h3>
    <hr />
    <form method="post" name='create_github_repo_form' action="{% url 'core:github_create_repo' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for='github_repo_name'>Enter Github Repo Name</label>
            <input class="form-control" name='github_repo_name' type='text' id='github_repo_name'>
        </div>
        <div class="form-group">
            <label for='github_repo_desc'>Enter Repo Description</label>
            <input class="form-control" name='github_repo_desc' type='text' id='github_repo_desc'>
        </div>
        <button class="btn btn-primary" type='submit'>Update Integration</button>
    </form>   
    {% else %}
    <div class="alert alert-danger" role="alert">
        {{ authorization_error_message }}
    </div>  
    {% endif %}
    {% else %}
    <div class="alert alert-danger" role="alert">
        {{ integration_error_message }} Please Go to <a href="{% url 'accounts:my_account' %}">My Account</a> page, to complete integration.
    </div>  
{% endif %}
</div>

{% endblock content %}