accounts/urls.py
from django.urls import path

from . import views
from .api import views as api_views

app_name = 'accounts'

urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('login/', views.UserLoginView.as_view(), name="login"),
    path('connect-github/', views.ConnectGithubView.as_view(), name='connect_github'),
    path('disconnect-github/', views.DisconnectGithubAccount.as_view(), name='disconnect_github'),
    path('my_account/', views.UserAccountUpdateView.as_view(), name='my_account'),
    path('register/', views.UserRegisterView.as_view(), name="register"),
    path('update-integration/', views.UpdateIntegrationView.as_view(), name='update_integration'),

    # api views
    path('api/v1/users_without_github/', api_views.UsersWithoutGithubView.as_view(), name='api_users_without_github'),
]

apigator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('auth/', include('allauth.urls')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.home, name="home"),
    path("github/create-repo/", views.CreateGitHubRepo.as_view(), name="github_create_repo"),
]

templates/components/navigation/FooterUnauthenticated.html
{% block footer %}
<footer class="footer bg-light py-2">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-auto">Developed by Manoj Tyagi</div>
      <div class="col-auto">
        <a href="#">Help</a>
      </div>
    </div>
  </div>
</footer>

{% endblock footer %}

templates/components/navigation/TopNavigationAuthenticated.html
{% block top_navigation %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'core:home' %}">APIGator</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'accounts:my_account' %}"><i class="fas fa-user"></i> My account</a>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </div>
            </li>
        </ul>
    </div>
    
  </div>
</nav>
{% endblock top_navigation %}

templates/components/navigation/TopNavigationUnauthenticated.html
{% block top_navigation %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">APIGator</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      class="collapse navbar-collapse justify-content-end"
      id="navbarNavAltMarkup"
    >
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="#">Get Started</a>
      </div>
    </div>
  </div>
</nav>
{% endblock top_navigation %}